### ISSUE TITLE
Why is this a template repository?

### ISSUE THREAD

**Issue by lil5** [rednafi/httpurr#14]
This just makes it difficult to contribute to, as repositories built by this template aren't able to contribute back to the original template.

**Comment by lil5** [comment]
To revert to a normal repo uncheck the checkbox here:

![Screenshot 2023-08-30 at 18 30 56](https://github.com/rednafi/httpurr/assets/17646836/fe116bdb-e26a-4c63-a7e9-fa3a5909cefa)

**Comment by rednafi** [comment]
I wasn't aware of this limitation. Un templating this.
