### ISSUE TITLE
Feature: Use charmbracelet's lipgloss to enhance output

### ISSUE THREAD

**Issue by kareemmahlees** [rednafi/httpurr#19]
Hi Redowan!
You have a nice and elegant piece of tool here good job 🌟.

I was proposing to use Charmbracelet's [lipgloss](https://github.com/charmbracelet/lipgloss) to style the output.
for example, coloring the header 2xx green making it bold, and so on.

If this is okay you can assign it to me and I will create a PR for it 🙂.
Also, if you could add the hactoberfest label  that would be awesome.

**Comment by rednafi** [comment]
Hi, thanks for the issue. Yeah, adding extra flare would be nice but not sure if that justifies adding an external dependency.
