### ISSUE TITLE
Default (without code flag) should work as well

### ISSUE THREAD

**Issue by lil5** [rednafi/httpurr#7]
`httpurr 410`

**Comment by rednafi** [comment]
Thanks, for the idea. It does save some extra bit of typing but now that [v0.1.1] has a couple of more flags, this will make things confusing. 

[v0.1.1]: https://github.com/rednafi/httpurr/releases/tag/v0.1.1

**Comment by deceptive-ai** [comment]
This is a bad idea.

**Comment by lil5** [comment]
@deceptive-ai come back to me in a month and see if you remember what flag to use to lookup a status code. 

I'll create a fork with this included anyway.

**Comment by deceptive-ai** [comment]
@lil5 Ever heard of a thing called `-help`?If not, you should check that out. **Glad this got turned down**. Ambiguous and nonsensical behaviors like this make things hard.

**Comment by rednafi** [comment]
@deceptive-ai If you don't have anything productive to add to the discussion, please don't spam here. This has been settled; please move on.
